# GitVersionScript.cmake
# Copyright 2023 Scott Bailey
# MIT License - please see `https://opensource.org/license/mit/` for more information.
#
# Inputs:
#
#     -DVERSION_PATH=${path_to_source_}
#     -DVERSION_NAME=${name_}
#     -DVERSION_FILE=${file_}


include("${CMAKE_CURRENT_LIST_DIR}/GitVersionSupport.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/date.cmake")

# get the data
GitVersionInfo( ${VERSION_PATH} url branch tag full_hash short_hash commit_time clean dirty_reason)


if(clean)
  set(is_clean "true")
else()
  set(is_clean "false")
endif()

expand_date(${commit_time} year doy)
year2("${year}" year2)
doy3("${doy}" doy3)


# Open a temporary version file and overwrite any existing data.
set(temp_file "${VERSION_FILE}.temp")
file(WRITE ${temp_file}  "" )

# This macro simply makes the following lines easier.
macro(write val)
  file(APPEND ${temp_file} "${val}\n")
endmacro()

# Write the data!
write( "/* AUTOGENERATED GIT VERSION INFO FILE -- PLEASE DO NOT HAND EDIT */" )
write( "" )
write( "#ifndef __${VERSION_NAME}_GIT_VERSION_FILE__" )
write( "#define __${VERSION_NAME}_GIT_VERSION_FILE__" )
write( "" )
write( "" )
if(clean)
  write( "#define ${VERSION_NAME}_IS_CLEAN" )
  write( "/* #define ${VERSION_NAME}_IS_DIRTY */" )
else()
  write( "/* #define ${VERSION_NAME}_IS_CLEAN */" )
  write( "#define ${VERSION_NAME}_IS_DIRTY" )
  write( "   /* DIRTY REASON: ${dirty_reason} */" )
endif()
write( "" )
write( "" )
write( "#define ${VERSION_NAME}_URL              \"${url}\"")
write( "#define ${VERSION_NAME}_BRANCH           \"${branch}\"")
write( "#define ${VERSION_NAME}_TAG              \"${tag}\"")
write( "" )
write( "#define ${VERSION_NAME}_FULL_HASH        ${full_hash}")
write( "#define ${VERSION_NAME}_SHORT_HASH       ${short_hash}")
write( "#define ${VERSION_NAME}_COMMIT_TIME      ${commit_time}")
write( "#define ${VERSION_NAME}_COMMIT_YEAR      ${year}")
write( "#define ${VERSION_NAME}_COMMIT_YEAR2     ${year2}")
write( "#define ${VERSION_NAME}_COMMIT_DOY       ${doy}")
write( "#define ${VERSION_NAME}_COMMIT_DOY3      ${doy3}")
write( "" )
write( "#define ${VERSION_NAME}_FULL_HASH_STR    \"${full_hash}\"")
write( "#define ${VERSION_NAME}_SHORT_HASH_STR   \"${short_hash}\"")
write( "#define ${VERSION_NAME}_COMMIT_YEAR_STR  \"${year}\"")
write( "#define ${VERSION_NAME}_COMMIT_YEAR2_STR \"${year2}\"")
write( "#define ${VERSION_NAME}_COMMIT_DOY_STR   \"${doy}\"")
write( "#define ${VERSION_NAME}_COMMIT_DOY3_STR  \"${doy3}\"")
write( "#define ${VERSION_NAME}_COMMIT_2D3_STR   \"${year2}.${doy3}\"")
write( "#define ${VERSION_NAME}_CLEAN            ${is_clean}" )
write( "" )
write( "" )
write( "#endif" )


# copy and cleanup
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${temp_file}" "${VERSION_FILE}")
file(REMOVE "${temp_file}")
